### ISSUE TITLE
Remove external script for code-mirror

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/formidable-landers#106]
Code Mirror is now included in `component-playground`, so remove the external script tags in `index.html` and `templates/index.hbs`. 

See https://github.com/FormidableLabs/component-playground/pull/55

**Comment by kylecesmat** [comment]
Looks to be a problem with webpack's `dedupePlugin` - For whatever reason it removes codemirror from the bundle.

https://github.com/FormidableLabs/builder-docs-archetype/blob/master/config/webpack/webpack.config.static.js#L38

**Comment by ryan-roemer** [comment]
@kylecesmat - can we get a full assessment of what the real issue is here with inspection of the js bundles? (Tip: add 'output.pathinfo = true' and disable uglify plugin in webpack configs that generate the final prod bundle)

And ask @divmain for debugging help - he's an expert with bundles and plugins!

**Comment by kylecesmat** [comment]
Might have been a configuration error on my part, I tried to reproduce it without any success, so I've moved forward with removing the scripts without issue
