### ISSUE TITLE
Document best practices for writing readme documentation

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/formidable-landers#117]
@bmathews What are your thoughts on the best way to create links in the markdown files for any future open-source repos? Would you be willing to document best practices, so we don't end up with broken links? 

If the static sites continue to use `marked`, what's the ideal way to create links between pages?

**Comment by bmathews** [comment]
Sure! Just some quick notes for discussion:

If a static site has `<base href="{path}" />`, relative links that work when viewing `.md` files on Github _won't_ work on the static site. When the `base` element is on a page, anchor links and relative links no longer behave the same as Github. To fix it, we have to customize how `marked` or `markdown-it` generate the links so that we can prefix relative links with the base path.

So, we should keep writing markdown files exactly the same as we have been so that they continue to work on Github, but we'll just need to make sure we're transforming them properly if a site has a base href.

**Comment by kylecesmat** [comment]
We should put this in the wiki!

**Comment by paulathevalley** [comment]
Done! https://github.com/FormidableLabs/formidable-landers/wiki/Best-Practices-for-Writing-.md
