### ISSUE TITLE
Handle loading state for Ecology/Component-playground

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/formidable-landers#23]
Thoughts? Is this possible? 

At minimum, could we set a minimum height to the playgrounds, so the jump isn’t so shocking?

![ecology-loooading](https://cloud.githubusercontent.com/assets/768965/11414672/02acd6d4-93ad-11e5-8f94-e1ed850a4869.gif)

**Comment by kylecesmat** [comment]
Diving into this issue, there are a few events happening
1. The markdown file is being parsed and serving the `codeblock` markup server-side.
2. Then, the playground component is loaded, which renders the codemirror-preview & component-preview.

I think there are two solutions:
1. Add a min-height. This may still be complicated and just as 'shocking' because it will still move the page. The complication comes from where do we attach the `min-height` styles? Because the playground component isn't rendered yet, we'd need to attach them to the plain `codeblock` I believe.
2. Never return a `codeblock`, figure out if we could parse the markdown file and immediately return the playground node with default loading content inside?

Still investigating...

**Comment by kylecesmat** [comment]
Will need to get merged/tagged:
- [ ] https://github.com/FormidableLabs/ecology/pull/41
- [ ] https://github.com/FormidableLabs/formidable-landers/pull/108

Will need `ecologyPlaygroundLoading` passed to Ecology component:
- [ ] victory-core/docs/victory-animation/docs
- [ ] victory-chart/docs/victory-area/docs
- [ ] victory-chart/docs/victory-axis/docs
- [ ] victory-chart/docs/victory-bar/docs
- [ ] victory-chart/docs/victory-chart/docs
- [ ] victory-core/docs/victory-label/docs
- [ ] victory-chart/docs/victory-line/docs
- [ ] victory-pie/docs/docs
- [ ] victory-chart/docs/victory-scatter/docs
