### ISSUE TITLE
Component playgrounds are not updating the live preview

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/formidable-landers#39]
http://projects.formidablelabs.com/victory/:
![0ceb0c3c-9cc3-11e5-85cf-7c08c05e6990](https://cloud.githubusercontent.com/assets/768965/11634112/890165a0-9cc3-11e5-8ae3-10a68d3b0355.png)

http://projects.formidablelabs.com/victory/docs/victory-axis:
(The rest of the component playgrounds behave except for this one.)
![screen shot 2015-12-07 at 9 17 46 am](https://cloud.githubusercontent.com/assets/768965/11634115/8fcfea6e-9cc3-11e5-9ba4-a27ff0ba13cc.png)

http://projects.formidablelabs.com/victory/docs/victory-scatter:
(The rest of the component playgrounds behave except for this one.)
![screen shot 2015-12-07 at 9 25 47 am](https://cloud.githubusercontent.com/assets/768965/11634289/872631c4-9cc4-11e5-9228-eef302280199.png)

**Comment by kenwheeler** [comment]
This is fixed in component playground 1.0.5.

What was happening was, in the midst of typing, undefined errors were being surfaced to the client, because they were technically valid at compile time. Only during the render were they exposed, so they bypassed the try catch. This was fixed by calling ReactDOMServer.renderToString on the markup before rendering, which does indeed surface the undefined error in the render before it makes it to the client.
