### ISSUE TITLE
Add copy/content for Builder landing page

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/formidable-landers#40]
@ryan-roemer Do you have an existing documentation/copy/content for the value of Builder, why it should be used, etc. that we can use for its landing page? 

(If not, @david-davidson will get in touch with you and put something together.)

**Comment by david-davidson** [comment]
Must-haves via @coopy and @paulathevalley:
```
- Want to start building a node archetype? [ Click here ] 
- Want to start building a style guide archetype? [ Click here ]
- Want to start building X archetype? [ Click here ]
```

**Comment by david-davidson** [comment]
I'm thinking that since 1.) we already have [a great README for builder](https://github.com/FormidableLabs/builder/blob/master/README.md) and 2.) we don't want competing sources of truth, the bulk of the docs site should just be the builder README itself, pulled in directly from the repo/npm.

Specifically:
* There'd be a short landing page at `builder.formidable.com`, with a high-level marketing-y overview and a `Get started` button.
  * Here's the WIP copy: https://docs.google.com/document/d/1HX3LoRiA_BQJZvb2ge22t4DOc2MiYIo9t837U4bsWwY/edit?usp=sharing
* There'd be a much longer page at `builder.formidable.com/docs`: the README, rendered as HTML in a fancy builder theme.
* If we can figure out how to do it, `/docs` would ideally parse the README and generate a sidebar of deep links within the page, to cut down on the wall-of-text effect.
* Content changes/additions (like adding instructions for how to build a node or style guide archetype, as captured above) would go straight into the README.

Does this approach sound good? /cc @ryan-roemer @paulathevalley @coopy

**Comment by paulathevalley** [comment]
![o-slsrocket-facebook](https://cloud.githubusercontent.com/assets/768965/12044267/7bf08b02-ae43-11e5-97a0-413203e478b9.jpg)
