### ISSUE TITLE
<Header/> link underline woes

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/formidable-landers#52]
The [`box-shadow` on the `a`](https://github.com/FormidableLabs/formidable-landers/blob/master/src/themes/victory.js#L124) in `formidable-landers/components/src/header.jsx` is applied to the whole element (not underlining the text node) when the parent `<header/>` element has `display: 'flex'`:

![screen shot 2016-01-13 at 3 15 48 pm](https://cloud.githubusercontent.com/assets/794843/12311948/f4b51bac-ba0f-11e5-8005-ee1002ee3c42.png)

The problem goes away if you set the parent style to `display: 'block'`:

![screen shot 2016-01-13 at 4 10 16 pm](https://cloud.githubusercontent.com/assets/794843/12311969/28d98a76-ba10-11e5-866b-9dccd8f67aae.png)

In the Victory lander, I used `styleOverrides` to work around this: https://github.com/FormidableLabs/victory/commit/53b67f0342ab5fa901953498e4f3433c4d008edd#diff-c66c131e4a2c77d8e2f9793283e3ac1dR32

I'd like this to be fixed upstream in the `<Header/>` component, if there's no objection.

/cc @paulathevalley

**Comment by paulathevalley** [comment]
Ok, so the `<Header />` does not need `display: flex`, but the `<Footer />` component _does_ need to keep `display: flex;` in order for the sticky footer magic to work. However, since each item there is wrapped in a `<span style={{display: block}}>` it does not run into this problem: 

<img width="643" alt="screen shot 2016-01-15 at 12 36 50 pm" src="https://cloud.githubusercontent.com/assets/768965/12364676/e14ff2a0-bb84-11e5-9e64-2ee1f87fb58b.png">

Question: Would it preferable to have both components match (therefore wrap the link in a `<span>`) or keep it simple and change `<Header/>` to be `display: block;`?

**Comment by coopy** [comment]
> Question: Would it preferable to have both components match (therefore wrap the link in a <span>)
Yes :]
